<?php

namespace Database\Seeders;

use App\Domain\System\Models\DevControl;
use Illuminate\Database\Seeder;

class DevControlSeeder extends Seeder
{
    public function run(): void
    {
        foreach (self::defaults() as $sort => $item) {
            DevControl::query()->updateOrCreate(
                ['module' => $item['module']],
                array_merge($item, ['sort_index' => $sort + 1]),
            );
        }
    }

    public static function defaults(): array
    {
        return [
            [
                'module' => 'Tenants/Companies',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'OK',
                'crud_api_status' => 'TODO',
                'filters_status' => 'OK',
                'list_ui_status' => 'OK',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Users/Auth',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'TODO',
                'crud_api_status' => 'TODO',
                'filters_status' => 'TBD',
                'list_ui_status' => 'TODO',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'CashBoxes',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'OK',
                'crud_api_status' => 'TODO',
                'filters_status' => 'OK',
                'list_ui_status' => 'OK',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Transactions',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'OK',
                'crud_api_status' => 'TODO',
                'filters_status' => 'OK',
                'list_ui_status' => 'OK',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Receipts',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'OK',
                'crud_api_status' => 'TODO',
                'filters_status' => 'OK',
                'list_ui_status' => 'OK',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Spendings',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'OK',
                'crud_api_status' => 'TODO',
                'filters_status' => 'OK',
                'list_ui_status' => 'OK',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'CashTransfers',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'TODO',
                'crud_api_status' => 'TODO',
                'filters_status' => 'TODO',
                'list_ui_status' => 'TODO',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'CashboxHistory',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'TODO',
                'crud_api_status' => 'TODO',
                'filters_status' => 'TBD',
                'list_ui_status' => 'TODO',
                'form_ui_status' => 'TBD',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Counterparties',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'TODO',
                'crud_api_status' => 'TODO',
                'filters_status' => 'TODO',
                'list_ui_status' => 'TODO',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Contracts',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'OK',
                'crud_api_status' => 'TODO',
                'filters_status' => 'TODO',
                'list_ui_status' => 'TODO',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Estimates',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'TODO',
                'crud_api_status' => 'TODO',
                'filters_status' => 'TODO',
                'list_ui_status' => 'TODO',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Products/Stock',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'TODO',
                'crud_api_status' => 'TODO',
                'filters_status' => 'TODO',
                'list_ui_status' => 'TODO',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Dashboards',
                'er_status' => 'OK',
                'model_status' => 'TBD',
                'list_api_status' => 'OK',
                'crud_api_status' => 'TODO',
                'filters_status' => 'TBD',
                'list_ui_status' => 'WIP',
                'form_ui_status' => 'TBD',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Roles/ACL',
                'er_status' => 'OK',
                'model_status' => 'TBD',
                'list_api_status' => 'TODO',
                'crud_api_status' => 'TODO',
                'filters_status' => 'TBD',
                'list_ui_status' => 'TODO',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Settings/Config',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'OK',
                'crud_api_status' => 'TODO',
                'filters_status' => 'Basic',
                'list_ui_status' => 'OK',
                'form_ui_status' => 'TODO',
                'tests_status' => 'TODO',
                'docs_status' => 'TODO',
                'deploy_status' => 'TODO',
            ],
            [
                'module' => 'Dev Control',
                'er_status' => 'OK',
                'model_status' => 'OK',
                'list_api_status' => 'OK',
                'crud_api_status' => 'WIP',
                'filters_status' => 'TBD',
                'list_ui_status' => 'OK',
                'form_ui_status' => 'TBD',
                'tests_status' => 'TODO',
                'docs_status' => 'WIP',
                'deploy_status' => 'TODO',
            ],
        ];
    }
}
