export default [
  { heading: 'Финансы' },
  { title: 'Транзакции', icon: { icon: 'tabler-arrows-right-left' }, to: { path: '/finance/transactions' } },
  { title: 'Неразнесенные', icon: { icon: 'tabler-inbox' }, to: { path: '/finance/unassigned' } },
  { title: 'Приходы', icon: { icon: 'tabler-arrow-down-right' }, to: { path: '/finance/receipts' } },
  { title: 'Расходы', icon: { icon: 'tabler-arrow-up-right' }, to: { path: '/finance/spendings' } },
  { title: 'Баланс', icon: { icon: 'tabler-scale' }, to: { path: '/finance/balance' } },
  { title: 'ОДДС', icon: { icon: 'tabler-report-money' }, to: { path: '/finance/cashflow' } },
  { title: 'CEO отчёты', icon: { icon: 'tabler-chart-line' }, to: { path: '/finance/reports' } },
  { heading: 'Товары' },
  { title: 'Товары', icon: { icon: 'tabler-box' }, to: { path: '/products' } },
  { title: 'Прайс', icon: { icon: 'tabler-currency-rubel' }, to: { path: '/products/price' } },
  { heading: 'Настройки' },
  {
    title: 'Шаблоны смет',
    icon: { icon: 'tabler-template' },
    children: [
      { title: 'Материалы', to: { path: '/estimate-templates/materials' } },
      { title: 'Септики', to: { path: '/estimate-templates/septiks' } },
    ],
  },
  { title: 'Шаблоны договоров', icon: { icon: 'tabler-file-text' }, to: { path: '/operations/contracts/templates' } },
  { title: 'Dev Control', icon: { icon: 'tabler-clipboard-list' }, to: { path: '/dev-control' } },
  {
    title: 'Справочники',
    icon: { icon: 'tabler-database' },
    children: [
      { title: 'Кассы', to: { path: '/settings/cash-boxes' } },
      { title: 'Компании', to: { path: '/settings/companies' } },
      { title: 'Права и роли', to: { path: '/settings/roles-permissions' } },
      { title: 'Фонды расходов', to: { path: '/settings/spending-funds' } },
      { title: 'Статьи расходов', to: { path: '/settings/spending-items' } },
      { title: 'Статьи ДДС', to: { path: '/settings/cashflow-items' } },
      { title: 'Статусы договоров', to: { path: '/settings/contract-statuses' } },
      { title: 'Типы транзакций', to: { path: '/settings/transaction-types' } },
      { title: 'Типы объектов учета', to: { path: '/settings/finance-object-types' } },
      { title: 'Типы продаж', to: { path: '/settings/sale-types' } },
      { title: 'Города', to: { path: '/settings/cities' } },
      { title: 'Районы', to: { path: '/settings/districts' } },
    ],
  },
  {
    title: 'Настройки ФОТ',
    icon: { icon: 'tabler-users' },
    children: [
      { title: 'Правила менеджеров', to: { path: '/settings/payroll' } },
      { title: 'Настройки маржи', to: { path: '/settings/margin' } },
    ],
  },
  { heading: 'СИСТЕМА', superadminOnly: true },
  {
    title: 'Логотипы',
    icon: { icon: 'tabler-brand-visa' },
    to: { path: '/system/logos' },
    superadminOnly: true,
  },
]
